package:
  name: assign_clades
  version: 0.0.0

source:
  git_url: https://github.com/DiDigsDNA/clade_assignment
  git_rev: v0.0.0
  folder: clade_assignment

requirements:
  run:
    - python
    - biopython

build:
  number: 0

about:
  home: https://github.com/DiDigsDNA/clade_assignment

